# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'PA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PA

  pod 'Alamofire'
  pod 'Nuke', '~> 7.0'

  target 'PATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
